spring.application.name=Erp-inventorymanagement

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Erpinventorymanagement-db
spring.datasource.username=postgres
spring.datasource.password=vijay123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
server.port=8080

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=VGhpcy1pcy1hLWxvbmctc2VjcmV0LWtleS1mb3ItanZ0LWF1dGg=
jwt.expiration=86400000
